"""Internal compatibility wrapper over the supervision-first data surface."""

from treepo._research.training.supervision.comparative_types import (
    DEFAULT_GLOBAL_PROPENSITY,
    MAX_PROPENSITY,
    MIN_PROPENSITY,
    ComparativeCandidate,
    ComparativeDataset,
    ComparativeJudgmentRecord,
    GenRMDeriver,
    GenerationConfig,
    JudgeDeriver,
    OracleDeriver,
    PreferenceDataset,
    PreferenceDerivationResult,
    PreferenceDeriver,
    PreferencePair,
    PromptBuilder,
    compute_propensity_diagnostics,
    get_deriver,
    list_derivers,
    register_deriver,
    render_prompt,
)
from treepo._research.training.supervision.types import (
    BinaryComparison,
    BinaryProjectionDataset,
    ComparativeJudgment,
    ResponseJudgment,
    SupervisionDataset,
    coerce_supervision_dataset,
)

__all__ = [
    "BinaryComparison",
    "BinaryProjectionDataset",
    "ComparativeCandidate",
    "ComparativeDataset",
    "ComparativeJudgment",
    "ComparativeJudgmentRecord",
    "DEFAULT_GLOBAL_PROPENSITY",
    "GenRMDeriver",
    "GenerationConfig",
    "JudgeDeriver",
    "MAX_PROPENSITY",
    "MIN_PROPENSITY",
    "OracleDeriver",
    "PreferenceDataset",
    "PreferenceDerivationResult",
    "PreferenceDeriver",
    "PreferencePair",
    "PromptBuilder",
    "ResponseJudgment",
    "SupervisionDataset",
    "coerce_supervision_dataset",
    "compute_propensity_diagnostics",
    "get_deriver",
    "list_derivers",
    "register_deriver",
    "render_prompt",
]
