"""Setup package for source-tree method vignettes.

Runnables import from this package as a stable facade; the implementation is
split by example family so one-off fixture plumbing stays out of the vignettes.
"""

from example_setup.common import (
    artifact_kind,
    config_dict,
    grid_values,
    load_example_config,
    metric,
    neural_operator_backend,
    parse_output_dir,
    result_metrics,
    result_statistics,
    write_json,
)
from example_setup.configs import (
    FnoMarkovConfig,
    HllSketchConfig,
    ManifestoEndToEndConfig,
    ManifestoReplicationConfig,
    ManifestoRewardMechanismConfig,
    NeuralOperatorCompareConfig,
    NeuralOperatorLDAConfig,
    NeuralOperatorLDALeafGridConfig,
    NeuralOperatorMarkovLeafGridConfig,
)
from example_setup.manifesto import (
    manifesto_finetune_fixture,
    manifesto_finetune_summary,
    manifesto_grid_cells,
    resolved_qsentence_sampling,
    run_manifesto_replication_cell,
    sample_desc,
)
from example_setup.synthetic import (
    fit_lda_sklearn_baseline,
    hll_fit_config,
    hll_trees,
    lda_average_guess_baseline,
    lda_fit_config,
    lda_grid_row,
    lda_split,
    lda_target_key,
    markov_average_guess_baseline,
    markov_fit_config,
    markov_grid_row,
    markov_preferences,
    markov_split,
    mean_topic_mae,
    validate_preference_mode,
)
from example_setup.toy_records import (
    toy_certificate_preferences,
    toy_dspy_fit_config,
    toy_error_certificate,
    toy_finetune_preferences,
    toy_local_law_rows,
    toy_optimizer_trees_and_preferences,
    toy_root_metrics,
    toy_statistic_artifact,
    write_local_law_rows,
)

__all__ = [
    "FnoMarkovConfig",
    "HllSketchConfig",
    "ManifestoEndToEndConfig",
    "ManifestoReplicationConfig",
    "ManifestoRewardMechanismConfig",
    "NeuralOperatorCompareConfig",
    "NeuralOperatorLDAConfig",
    "NeuralOperatorLDALeafGridConfig",
    "NeuralOperatorMarkovLeafGridConfig",
    "artifact_kind",
    "config_dict",
    "fit_lda_sklearn_baseline",
    "grid_values",
    "hll_fit_config",
    "hll_trees",
    "lda_average_guess_baseline",
    "lda_fit_config",
    "lda_grid_row",
    "lda_split",
    "lda_target_key",
    "load_example_config",
    "manifesto_finetune_fixture",
    "manifesto_finetune_summary",
    "manifesto_grid_cells",
    "markov_average_guess_baseline",
    "markov_fit_config",
    "markov_grid_row",
    "markov_preferences",
    "markov_split",
    "mean_topic_mae",
    "metric",
    "neural_operator_backend",
    "parse_output_dir",
    "resolved_qsentence_sampling",
    "result_metrics",
    "result_statistics",
    "run_manifesto_replication_cell",
    "sample_desc",
    "toy_certificate_preferences",
    "toy_dspy_fit_config",
    "toy_error_certificate",
    "toy_finetune_preferences",
    "toy_local_law_rows",
    "toy_optimizer_trees_and_preferences",
    "toy_root_metrics",
    "toy_statistic_artifact",
    "validate_preference_mode",
    "write_json",
    "write_local_law_rows",
]

