from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping

from treepo._research.unified_g_v1.core.contracts import MarkovRunSpec
from treepo._research.unified_g_v1.markov.runner import MarkovRunRecord, run_markov_spec


def run_markov_synthetic(
    *,
    run_spec: MarkovRunSpec,
    output_dir: Path,
    use_cuda: bool = True,
    cuda_device: int | None = None,
    torch_threads: int = 0,
    reuse_existing: bool = True,
    config_overrides: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Thin adapter: calls `run_markov_spec` and returns a FitResult-shaped dict.

    Synthetic Markov runs do not consume a PreparedDataset — their data is
    generated by `materialize_scope_bundle` inside `run_markov_spec`.
    """
    record: MarkovRunRecord = run_markov_spec(
        run_spec,
        output_root=output_dir,
        use_cuda=bool(use_cuda),
        cuda_device=cuda_device,
        torch_threads=int(torch_threads),
        reuse_existing=bool(reuse_existing),
        config_overrides=config_overrides,
    )
    return {
        "backend": "markov_synthetic",
        "run_key": record.spec.run_key,
        "summary_path": str(record.summary_path),
        "run_dir": str(record.run_dir),
        "extracted_metrics": dict(record.extracted_metrics),
        "program_contract": dict(record.program_contract),
        "training_geometry": dict(record.training_geometry),
        "local_law_learnability": dict(record.local_law_learnability),
        "record": record,
    }
