"""Unified-G V1 parallel lane."""

from .bundles import (
    build_openai_record_eval_bundle,
    create_text_artifact_bundle,
    run_embedding_fno_train_bundle,
    run_embedding_sequence_smoke_bundle,
    run_preference_data_bundle,
    run_preference_optimization_bundle,
    run_record_eval_bundle,
    run_text_audit_bundle,
    run_text_batch_bundle,
    run_text_dspy_optimize_bundle,
    run_dspy_rile_bundle,
    run_dspy_rile_tree_bundle,
    run_text_llm_trl_sft_bundle,
    run_token_sequence_fno_report_bundle,
    run_token_sequence_fno_smoke_bundle,
)
from .bundle_runner import (
    BundleApproach,
    BundleRunSpec,
    launch_bundle_collection,
    list_bundle_approaches,
    load_bundle_collection_config,
    parse_bundle_run_spec,
    run_bundle,
    run_bundle_collection,
)
from .core.artifact import (
    LLMTextUnifiedFGProgram,
    TextUnifiedGProgram,
    UnifiedGArtifact,
    build_llm_text_unified_fg_contract,
    build_text_unified_g_contract,
    build_unified_dspy_strategy,
    resolve_text_unified_g_program,
)
from .core.contracts import (
    ComparatorPolicy,
    MarkovRunSpec,
    MarkovScope,
    Profile,
    SupervisionPolicy,
)
from .core.program import UnifiedFGProgram, UnifiedGContract, UnifiedGProgram, UnifiedGSurface
from .core.splits import (
    DocumentSplitIds,
    load_phase1_split_ids,
    load_split_ids_json,
    resolve_document_split_ids,
    write_split_ids_json,
)
from .core.specs import (
    LearnerSpec,
    SpaceSpec,
    UnifiedFGSpec,
    build_token_sequence_fno_program_spec,
    build_ctreepo_program_spec,
    build_embedding_sequence_fno_program_spec,
    build_llm_text_program_spec,
    build_markov_token_fno_program_spec,
    build_mergeable_sketch_program_spec,
    build_program_family,
    build_semantic_embedding_program_spec,
    resolve_program_spec_alias,
)
from .core.tensor_program import (
    EmbeddingOperatorUnifiedFGProgram,
    NeuralOperatorFHead,
    build_embedding_operator_unified_fg_program,
    build_embedding_unified_g_program,
    resolve_operator_head_width,
)
from .markov.program import (
    MarkovPrediction,
    MarkovSummarySurface,
    MarkovTreeState,
    MarkovUnifiedFGProgram,
    MarkovUnifiedGBinding,
    build_markov_unified_fg_program,
    resolve_markov_unified_fg_program,
    resolve_markov_unified_g_binding,
)
from .markov.runner import run_fixed_report_suite, run_markov_spec
from .markov.smoke import run_markov_smoke_suite
from .realdoc.embedding import HashEmbeddingClient, run_manifesto_embedding_smoke
from .realdoc.embedding_fno_training import (
    EmbeddingFNOTrainingConfig,
    EmbeddingSequenceFNOTreeModel,
    load_phase1_split_ids,
    run_embedding_fno_training,
)
from .realdoc.dspy_optimize import LawStressDSPyOptimizeConfig

TextDSPyOptimizeConfig = LawStressDSPyOptimizeConfig

__all__ = [
    "ComparatorPolicy",
    "BundleApproach",
    "BundleRunSpec",
    "EmbeddingFNOTrainingConfig",
    "EmbeddingSequenceFNOTreeModel",
    "DocumentSplitIds",
    "HashEmbeddingClient",
    "EmbeddingOperatorUnifiedFGProgram",
    "LearnerSpec",
    "LLMTextUnifiedFGProgram",
    "TextDSPyOptimizeConfig",
    "TextUnifiedGProgram",
    "NeuralOperatorFHead",
    "SpaceSpec",
    "UnifiedFGSpec",
    "UnifiedFGProgram",
    "UnifiedGContract",
    "UnifiedGArtifact",
    "UnifiedGProgram",
    "UnifiedGSurface",
    "build_ctreepo_program_spec",
    "build_openai_record_eval_bundle",
    "build_embedding_operator_unified_fg_program",
    "build_embedding_sequence_fno_program_spec",
    "build_token_sequence_fno_program_spec",
    "build_embedding_unified_g_program",
    "build_llm_text_program_spec",
    "build_mergeable_sketch_program_spec",
    "build_program_family",
    "build_llm_text_unified_fg_contract",
    "build_text_unified_g_contract",
    "build_unified_dspy_strategy",
    "build_semantic_embedding_program_spec",
    "create_text_artifact_bundle",
    "launch_bundle_collection",
    "list_bundle_approaches",
    "load_bundle_collection_config",
    "load_phase1_split_ids",
    "load_split_ids_json",
    "parse_bundle_run_spec",
    "resolve_document_split_ids",
    "resolve_operator_head_width",
    "resolve_program_spec_alias",
    "resolve_text_unified_g_program",
    "run_bundle",
    "run_bundle_collection",
    "run_embedding_fno_training",
    "run_preference_data_bundle",
    "run_preference_optimization_bundle",
    "run_record_eval_bundle",
    "run_text_audit_bundle",
    "run_text_batch_bundle",
    "run_text_dspy_optimize_bundle",
    "run_dspy_rile_bundle",
    "run_dspy_rile_tree_bundle",
    "run_text_llm_trl_sft_bundle",
    "run_embedding_sequence_smoke_bundle",
    "run_embedding_fno_train_bundle",
    "run_token_sequence_fno_report_bundle",
    "run_token_sequence_fno_smoke_bundle",
    "write_split_ids_json",
]
